refactor(start.sh): transfer to run.py
MapColonies/osm-seed pull request #12
Opened 2020-09-21 11:14 UTC by galta95

2020-09-21 20:22 UTC, syncush requested changes
There are still magic rows like bash, lets discuss it later

2020-09-29 11:49 UTC, syncush requested changes

2020-09-29 11:49 UTC, syncush commented on tiler-osm2pgsql/Dockerfile
> +COPY ./run.py .
move `COPY ./run.py` after imports of configs, for better docker image layers caching

2020-09-29 11:49 UTC, syncush commented on tiler-osm2pgsql/run.py
> +            time.sleep(int(interval))
`interval = os.environ['OSM2PGSQL_UPDATE_INTERVAL']` => `interval = int(os.environ['OSM2PGSQL_UPDATE_INTERVAL'])` so you don't need to cast everytime you do `time.sleep`

2020-09-29 11:49 UTC, syncush commented on tiler-osm2pgsql/run.py
> +        state = parse_integer_to_directory_number(int(i % 1000))
extract the magic numbers into constants with a good name, why 1000000? 1000?

2020-09-29 11:49 UTC, syncush commented on tiler-osm2pgsql/run.py
> +        time.sleep(int(interval))
nesting is too big.
Always prefer 
```python
if  not boolean:
  code
code
code
code
code
```
then
```python
if boolean:
  code
  code
  code
  code
  code
  code
code
```
here you can do something like this:
```python
if  ( not is_file_or_directory(replication_state_file_path)):
    time.sleep(int(interval))
    continue
replication_state_file = open(replication_state_file_path)
replication_state_file_content = replication_state_file.read()

try:
    sequence_number = extract_integer_value(replication_state_file_content, "sequenceNumber")
except:
    raise ValueError("sequence_number must be positive integer at state.txt")
try:
    last_append = extract_integer_value(replication_state_file_content, "lastAppend")
except:
    last_append = -1

replication_state_file.close()

if (last_append != sequence_number):
    expired_state_file_path = os.path.join(expired_directory, "state.txt")

    if (is_file_or_directory(expired_state_file_path)):
        expired_file = open(f"{expired_directory}/state.txt")
        expired_file.close()

    update_replication_tiles(sequence_number, last_append)
    update_state_file(expired_state_file_path, sequence_number, last_append)

```

2020-09-29 11:49 UTC, syncush commented on tiler-osm2pgsql/run.py
> +    expired_file.close()
correct me if I am wrong but using `with open()` means python will automatically close the file for you once the `with`  scope is done.

2020-09-29 11:49 UTC, syncush commented on tiler-osm2pgsql/run.py
> +                update_state_file(expired_state_file_path, sequence_number, last_append)
this can be extracted to a function with a pretty name

2020-09-29 12:32 UTC, galta95 commented on tiler-osm2pgsql/Dockerfile
> +COPY ./run.py .
done

2020-09-29 12:32 UTC, galta95 commented on tiler-osm2pgsql/run.py
> +            time.sleep(int(interval))
done

2020-09-29 12:36 UTC, galta95 commented on tiler-osm2pgsql/run.py
> +        time.sleep(int(interval))
but what happens if the file isn't ready after the sleep? it's still continues the run? if yes - it's bad because the program will crash for not fount file :/

2020-09-29 12:38 UTC, galta95 commented on tiler-osm2pgsql/run.py
> +    expired_file.close()
You are right, "Notice, that we didn’t have to write “file.close()”. That will automatically be called."

2020-09-29 12:38 UTC, galta95 commented on tiler-osm2pgsql/run.py
> +    expired_file.close()
done

2020-09-29 13:16 UTC, syncush commented on tiler-osm2pgsql/run.py
> +        time.sleep(int(interval))
if the file not found then sleep -> wake up to next iteration loop and check if file exists.

It is the same code, just switched the statements, am I wrong?

2020-09-30 06:25 UTC, galta95 commented on tiler-osm2pgsql/run.py
> +                update_state_file(expired_state_file_path, sequence_number, last_append)
done

2020-09-30 06:28 UTC, galta95 commented on tiler-osm2pgsql/run.py
> +        time.sleep(int(interval))
done

2020-09-30 06:51 UTC, galta95 commented on tiler-osm2pgsql/run.py
> +        state = parse_integer_to_directory_number(int(i % 1000))
done

2020-09-30 07:23 UTC, syncush requested changes
Great, the script looks good!
Now all its missing are the logs.

2020-10-22 07:46 UTC, CptSchnitz requested changes
When you still install the packages for the logger, It is better to use a requirements.txt file and state the packages required there.
requirements.txt
```
python-json-logger==<SOME_VERSION>
mapcoloniesjsonlogger
```
and then copy the file and change the install in the dockerfile:
```
pip install -r requirements.txt
```
more info: 
https://pip.pypa.io/en/stable/reference/pip_install/#pip-install-examples
https://pip.pypa.io/en/stable/user_guide/#requirements-files

2020-10-25 13:10 UTC, CptSchnitz requested changes

2020-10-25 13:18 UTC, galta95 commented on tiler-osm2pgsql/config/requirements.txt
> +mapcoloniesjsonlogger==0.0.14
done

2020-10-25 13:19 UTC, galta95 commented on tiler-osm2pgsql/config/requirements.txt
> +postgresql-client
done

2020-10-25 13:37 UTC, CptSchnitz commented on tiler-osm2pgsql/Dockerfile
>  RUN git clone git://github.com/openstreetmap/osm2pgsql.git && \
Like in other containers we need to choose a specific version of the repo so it will always have the same build result.
just add:
```
git checkout c4c66d0faf6a4883f054d0a05e8928dd9b2b539f 
```

2020-11-01 15:03 UTC, closed without merging